# Generated by Django 5.1.7 on 2025-04-01 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_pedido_direccion_entrega_pedido_metodo_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora cuando se generó la factura', verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite de pago de la factura', null=True, verbose_name='Fecha de vencimiento')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total a pagar en la factura', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total')),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='Valor del IVA calculado', max_digits=12, verbose_name='IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Valor antes de aplicar impuestos', max_digits=12, verbose_name='Subtotal')),
                ('numero_factura', models.CharField(editable=False, help_text='Número único de identificación de la factura', max_length=20, unique=True, verbose_name='Número de factura')),
                ('estado', models.CharField(choices=[('P', 'Pagada'), ('N', 'Pendiente'), ('A', 'Anulada')], default='N', help_text='Estado actual de la factura', max_length=1, verbose_name='Estado')),
                ('metodo_pago', models.CharField(blank=True, help_text='Forma en que se realizó el pago', max_length=50, null=True, verbose_name='Método de pago')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Documento PDF generado para la factura', null=True, upload_to='facturas/%Y/%m/%d', verbose_name='Archivo PDF')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la factura', null=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(help_text='Usuario que generó la factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('pedido', models.OneToOneField(help_text='Pedido al que pertenece esta factura', on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='pedidos.pedido', verbose_name='Pedido asociado')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
                'permissions': [('view_all_facturas', 'Puede ver todas las facturas'), ('change_estado_factura', 'Puede cambiar el estado de factura'), ('anular_factura', 'Puede anular facturas')],
                'indexes': [models.Index(fields=['numero_factura'], name='facturas_fa_numero__8c84bb_idx'), models.Index(fields=['estado'], name='facturas_fa_estado_de2e38_idx'), models.Index(fields=['fecha_emision'], name='facturas_fa_fecha_e_6a1db1_idx')],
            },
        ),
    ]
