# Generated by Django 5.1.7 on 2025-04-01 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion_entrega_pedido_metodo_entrega_and_more'),
        ('productos', '0007_producto_vendedor_producto_producto_vendedor_idx'),
        ('usuarios', '0007_alter_usuario_groups_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Ítem de pedido', 'verbose_name_plural': 'Ítems de pedido'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ubicacion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.ubicacion', verbose_name='Ubicación de entrega'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido asociado'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Dirección de entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('en_proceso', 'En Proceso'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente_pago', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_entrega',
            field=models.CharField(choices=[('domicilio', 'A domicilio'), ('retirar', 'Retirar en tienda')], default='domicilio', max_length=10, verbose_name='Método de entrega'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total del pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.usuario', verbose_name='Comprador'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario'], name='pedido_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedido_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_creacion'], name='pedido_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_producto_en_pedido'),
        ),
    ]
