# Generated by Django 5.1.7 on 2025-03-31 08:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/%Y/%m/%d/', verbose_name='Imagen adicional')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de productos',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/%Y/%m/%d/', verbose_name='Imagen de categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto destacado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d/', verbose_name='Imagen principal'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre'], name='categoria_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activo'], name='categoria_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='producto_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['destacado'], name='producto_destacado_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio'], name='producto_precio_idx'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together={('producto', 'orden')},
        ),
    ]
