# Generated by Django 5.1.7 on 2025-03-31 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_imagenproducto_categoria_activo_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Ruta del archivo en el directorio static. Ej: icons/categoria.png', max_length=255, verbose_name='Icono (ruta estática)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Determina el orden de aparición en listados', verbose_name='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible en frontend'),
        ),
    ]
