# Generated by Django 5.1.7 on 2025-03-31 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_categoria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imagenproducto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='producto_precio_idx',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de descuento'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
