# Generated by Django 5.1.7 on 2025-04-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_imagenproducto_unique_together_and_more'),
        ('usuarios', '0007_alter_usuario_groups_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_vendidos', to='usuarios.usuario', verbose_name='Vendedor'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['vendedor'], name='producto_vendedor_idx'),
        ),
    ]
