# Generated by Django 5.1.7 on 2025-03-18 22:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_direccion_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='00000000', help_text='Ingrese su número de cédula (solo números).', max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Ej. +58 212 1235678', max_length=128, null=True, region='VE', unique=True, verbose_name='Número de teléfono'),
        ),
    ]
