# Generated by Django 5.1.7 on 2025-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(help_text='Ingrese su número de cédula (solo números).', max_length=20, unique=True, verbose_name='Cédula'),
        ),
    ]
