# Generated by Django 5.1.7 on 2025-04-01 05:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0006_alter_usuario_managers_remove_usuario_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='...', related_name='usuarios_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='...', related_name='usuarios_user_permissions', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ZELLE', 'Zelle'), ('BINANCE', 'Binance'), ('PAGO_MOVIL', 'Pago Móvil')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('email_zelle', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_zelle', models.CharField(blank=True, max_length=20)),
                ('email_binance', models.EmailField(blank=True, max_length=254, null=True)),
                ('banco_pago_movil', models.CharField(blank=True, choices=[('0102', 'Banco de Venezuela'), ('0104', 'Venezolano de Crédito'), ('0105', 'Banco Mercantil'), ('0108', 'Banco Provincial'), ('0114', 'Bancaribe'), ('0115', 'Banco Exterior'), ('0116', 'Banco Occidental de Descuento (BOD)'), ('0128', 'Banco Caroní'), ('0134', 'Banesco'), ('0137', 'Banco Sofitasa'), ('0138', 'Banco Plaza'), ('0146', 'Banco de la Gente Emprendedora'), ('0151', 'BFC Banco Fondo Común'), ('0156', '100% Banco'), ('0157', 'DelSur Banco Universal'), ('0163', 'Banco del Tesoro'), ('0166', 'Banco Agrícola de Venezuela'), ('0168', 'Bancrecer'), ('0169', 'Mi Banco'), ('0171', 'Banco Activo'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Banco Bicentenario'), ('0177', 'Banco de la Fuerza Armada Nacional Bolivariana (Banfanb)')], max_length=4)),
                ('telefono_pago_movil', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='VE')),
                ('cedula_pago_movil', models.CharField(blank=True, max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('AMA', 'Amazonas'), ('ANZ', 'Anzoátegui'), ('APU', 'Apure'), ('ARA', 'Aragua'), ('BAR', 'Barinas'), ('BOL', 'Bolívar'), ('CAR', 'Carabobo'), ('COJ', 'Cojedes'), ('DEL', 'Delta Amacuro'), ('FAL', 'Falcón'), ('GUA', 'Guárico'), ('LAR', 'Lara'), ('MER', 'Mérida'), ('MIR', 'Miranda'), ('MON', 'Monagas'), ('NES', 'Nueva Esparta'), ('POR', 'Portuguesa'), ('SUC', 'Sucre'), ('TAC', 'Táchira'), ('TRU', 'Trujillo'), ('VAR', 'Vargas'), ('YAR', 'Yaracuy'), ('ZUL', 'Zulia')], max_length=3)),
                ('municipio', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('direccion_exacta', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='usuarios.usuario')),
            ],
        ),
    ]
