# Generated by Django 5.1.7 on 2025-03-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
